GET http://localhost:3000/
###
DELETE http://localhost:3000/songs/2
###
PUT  http://localhost:3000/songs/3
Content-Type: application/json 

{
    "title":"latest song",
    "artist":["Drake"],
    "releaseDate":"2024-08-02",
    "duration":"04:34",
    "lyrics": "HOw about now"
}

# ###
# GET http://localhost:3000/songs/?page=4&limit=2
# ###

###

GET http://localhost:3000/songs/
###
GET http://localhost:3000/songs/8
###
###
POST http://localhost:3000/songs
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbmdhcnJpeEBnbWFpbC5jb20iLCJ1c2VySWQiOjE2LCJhcnRpc3RJZCI6NSwiaWF0IjoxNzEzNjkzMzU5LCJleHAiOjE3MTM3Nzk3NTl9.y_EKqiEGvwlmyWWbTwiSXTKy6i-oni4srlWZJ2QzF5w

{
    "title":"The fall off",
    "artist":[16 ],
    "releaseDate":"2027-09-02",
    "duration":"04:34",
    "lyrics": "hgfdsasdfghjk"
}


###
DELETE http://localhost:3000/songs/1
###
PUT http://localhost:3000/songs/8


### create a new playlist

POST http://localhost:3000/playlists
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbmdhcnJpeEBnbWFpbC5jb20iLCJ1c2VySWQiOjE2LCJhcnRpc3RJZCI6NSwiaWF0IjoxNzEzNjkzMzU5LCJleHAiOjE3MTM3Nzk3NTl9.y_EKqiEGvwlmyWWbTwiSXTKy6i-oni4srlWZJ2QzF5w

{
    "name": "liked songs",
    "songs" : [
        8
    ],
    "user": 1
}

### Sign up a user route
POST  http://localhost:3000/auth/signup
Content-Type: application/json 

{
    "firstName": "Martin",
    "lastName": "Garrix",
    "email": "martingarrix@gmail.com",
    "password": "password"

}

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "martingarrix@gmail.com",
    "password": "password"

}

### access token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwic3ViIjoyMDAwMDAwLCJpYXQiOjE3MTM2MzkzNTIsImV4cCI6MTcxMzcyNTc1Mn0.qDbodlIEiFziramIenBVc74Aw25f5nuchcySdfTpEAo
### getProfile

GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbmdhcnJpeEBnbWFpbC5jb20iLCJ1c2VySWQiOjE2LCJhcnRpc3RJZCI6NSwiaWF0IjoxNzEzNjkzMzU5LCJleHAiOjE3MTM3Nzk3NTl9.y_EKqiEGvwlmyWWbTwiSXTKy6i-oni4srlWZJ2QzF5w
