GET http://localhost:3000/
###
DELETE http://localhost:3000/songs/2
###
PUT  http://localhost:3000/songs/3
Content-Type: application/json 

{
    "title":"Costa Rica",
    "artist":["DREAMVILEE ", "J.I.D"],
    "releaseDate":"2023-09-29",
    "duration":"04:34",
    "lyrics": "fafafadfan sdfaslfas fsaldfas df"
}

###
GET http://localhost:3000/songs/?page=4&limit=2
###
GET http://localhost:3000/songs/2
###
###
POST http://localhost:3000/songs
Content-Type: application/json 

{
    "title":"LIKE THAT",
    "artist":["DAMIAN", "BUJU BANTON"],
    "releaseDate":"2023-09-29",
    "duration":"04:34",
    "lyrics": "THE QUICK BROWN FOX JUMPED OVER THE LAZY DOGS"
}


###
DELETE http://localhost:3000/songs/1
###
PUT http://localhost:3000/songs/1

