GET http://localhost:3000/
###
GET http://localhost:3000/songs
###
GET http://localhost:3000/songs/re
###
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title":"First Person Shooter",
    "artist":["nm"],
    "releaseDate":"2022-09-29",
    "duration":"02:34"
}


###
DELETE http://localhost:3000/songs/1
###
PUT http://localhost:3000/songs/1

